nome = str(input('digite seu nome completo? ')).strip()
print('analisando seu nome...')
print('seu nome em maíusculas é {}'.format(nome.upper()))
print('seu nome em mínusculas é {}'.format(nome.lower()))
print('seu nome ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))